### PR TITLE
Update xfinity.ts

### LINKED ISSUE #20: Browser Error: TimeoutError: waiting for selector `#user` failed: timeout 30000ms exceeded
Getting this fancy new error when the container runs, and it's happening right after Xfinity forced another password reset. On resetting the password and running the latest, it fails to update and gives

`Browser Error: TimeoutError: waiting for selector `#user` failed: timeout 30000ms exceeded`

And I'm now newly unable to access the password reset site (or any login.xfinity.com page including oath.xfinity.com) from my WAN IP. If I connect on my phone with mobile data or using a VPN, it works correctly.

This is one heck of a game of cat and mouse Xfinity is playing, and them restricting my ability to log into my account at all (to check email, to pay my bill -- anything) might be what makes me pull the plug on this, as useful as it is.

### PR DESCRIPTION
**Pull request by chrisjsmithnz**
Updates for new xfinity logon form, to cater for username prompt then password prompt rather than dual prompt.  Working locally, fixes #20.

### CODE REVIEW

**Comment by zachowj** [comment]
I am not seeing a new login form. Do you happen to have a screenshot and a source dump of it?

**Comment by chrisjsmithnz** [comment]
Logon
>

To me it looks like the existing is looking for the password field to appear, however it never does until a username is entered and submitted.

**Comment by mrulrich1** [comment]
I'm now having the same issue with `No node found for selector: #passwd` showing up in the error logs. Issue is exactly as described above.

**Comment by zachowj** [comment]
yes, it looks like they rolled out the changes to most users now.

**Pull request merged**
